#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import statistics
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

METHOD_LABELS = {
    "laplace": "laplace (baseline)",
    "laplace_basic1": "basic1",
    "laplace_basic2": "basic2",
    "laplace_advanced": "advanced",
}
METHOD_COLORS = {
    "laplace_basic1": "#1f77b4",
    "laplace_basic2": "#ff7f0e",
    "laplace_advanced": "#2ca02c",
}
METHOD_ORDER = ["laplace_basic1", "laplace_basic2", "laplace_advanced"]
BASELINE = "laplace"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot speedup charts for the Laplace MPI benchmarks from the generated CSV file."
    )
    parser.add_argument("input_csv", type=Path, help="Benchmark CSV generated by benchmark_laplace.py.")
    parser.add_argument("output_path", type=Path, help="Output image path (for example PNG or PDF).")
    parser.add_argument(
        "--show-error-bars",
        action="store_true",
        help="Show standard deviation error bars when the CSV contains repeated measurements.",
    )
    return parser.parse_args()


def load_rows(input_csv: Path) -> list[dict[str, str]]:
    with input_csv.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def group_speedups(rows: list[dict[str, str]]) -> dict[int, dict[str, dict[int, list[float]]]]:
    grouped: dict[int, dict[str, dict[int, list[float]]]] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for row in rows:
        source = row["source"]
        size = int(row["size"])
        nprocs = int(row["nprocs"])
        if source == BASELINE:
            continue
        if "speedup_vs_laplace" in row and row["speedup_vs_laplace"]:
            speedup = float(row["speedup_vs_laplace"])
        else:
            raise ValueError("CSV is missing speedup_vs_laplace values")
        grouped[nprocs][source][size].append(speedup)
    return grouped


def group_baseline(rows: list[dict[str, str]]) -> dict[int, dict[int, list[float]]]:
    grouped: dict[int, dict[int, list[float]]] = defaultdict(lambda: defaultdict(list))
    for row in rows:
        if row["source"] != BASELINE:
            continue
        size = int(row["size"])
        nprocs = int(row["nprocs"])
        grouped[nprocs][size].append(float(row["mean_sec"]))
    return grouped


def summarize(values: list[float]) -> tuple[float, float]:
    mean_value = statistics.mean(values)
    if len(values) < 2:
        return mean_value, 0.0
    return mean_value, statistics.stdev(values)


def plot_speedup(rows: list[dict[str, str]], output_path: Path, show_error_bars: bool) -> None:
    grouped_speedup = group_speedups(rows)
    baseline_times = group_baseline(rows)
    process_counts = sorted(grouped_speedup.keys())
    if not process_counts:
        raise ValueError("No non-baseline rows were found in the CSV")

    fig, axes = plt.subplots(
        nrows=len(process_counts),
        ncols=1,
        figsize=(11, max(4.5, 3.8 * len(process_counts))),
        sharex=True,
        constrained_layout=True,
    )
    if len(process_counts) == 1:
        axes = [axes]

    for axis, nprocs in zip(axes, process_counts):
        baseline_series = baseline_times.get(nprocs, {})
        sizes = sorted(baseline_series.keys())
        if not sizes:
            raise ValueError(f"No baseline data found for nprocs={nprocs}")

        axis.axhline(1.0, color="#444444", linestyle="--", linewidth=1.2, label="baseline = 1.0x")

        for source in METHOD_ORDER:
            source_series = grouped_speedup.get(nprocs, {}).get(source, {})
            if not source_series:
                continue

            x_values = sorted(source_series.keys())
            y_means = []
            y_errors = []
            for size in x_values:
                mean_value, stdev_value = summarize(source_series[size])
                y_means.append(mean_value)
                y_errors.append(stdev_value)

            color = METHOD_COLORS[source]
            label = METHOD_LABELS[source]
            if show_error_bars:
                axis.errorbar(
                    x_values,
                    y_means,
                    yerr=y_errors,
                    marker="o",
                    linewidth=2,
                    markersize=7,
                    color=color,
                    label=label,
                    capsize=4,
                )
            else:
                axis.plot(
                    x_values,
                    y_means,
                    marker="o",
                    linewidth=2,
                    markersize=7,
                    color=color,
                    label=label,
                )

            for x_value, y_value in zip(x_values, y_means):
                axis.annotate(
                    f"{y_value:.2f}x",
                    xy=(x_value, y_value),
                    xytext=(0, 8),
                    textcoords="offset points",
                    ha="center",
                    fontsize=9,
                    color=color,
                )

        axis.set_title(f"MPI process count: {nprocs}")
        axis.set_ylabel("Speedup vs baseline")
        axis.grid(True, linestyle="--", alpha=0.35)
        axis.set_xticks(sizes)
        axis.legend(loc="best")
        axis.set_ylim(bottom=0)

    axes[-1].set_xlabel("Grid size N")
    fig.suptitle("Laplace MPI optimization speedup relative to laplace.c", fontsize=15)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    args = parse_args()
    rows = load_rows(args.input_csv)
    plot_speedup(rows, args.output_path, args.show_error_bars)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
